### ISSUE TITLE
Possible without /build and /content subdirectories?

### ISSUE THREAD

**Issue by InteXX** [Matheos96/any-file-in-nuget-package#1]
I like your sample, and I'd like to use it, but I'm still a little bit lost. I have a `MyKey.lic` file in the project's root directory, and I want it to be copied into the package consumer's output directory. I'd prefer not to use /build and /content subdirectories anywhere in the project.

How would I get this to work using these constraints?

**Comment by Matheos96** [comment]
I'm glad you are interested in the example :)

You can definately do this without any build or contents folders, especially if you actually DO have a project and it is a .NET/.NET Standard/.NET Framework project. The example in this repo was actually made some time ago, before I knew of better and smarter ways of doing this exact thing WHEN you have a .csproj at hand and your consuming project is .NET (I have had trouble with copying to ouput with .NET Framework consumers using the method I am about to describe).

### The better way
This way we don't need to create a `.nuspec` manually at all. We will use `dotnet` rather than `nuget.exe`.
Assuming your described setup, `MyKey.lic` in the project root, add the following ItemGroup to your .csproj file:
```
<ItemGroup>
  <Content Include="MyKey.lic">
      <Pack>true</Pack>
      <PackageCopyToOutput>true</PackageCopyToOutput>
  </Content>
</ItemGroup>
```
Add your meta data for your package to your .csproj too, for example
```
<PropertyGroup>
  <TargetFramework>net9.0</TargetFramework>
  <ImplicitUsings>enable</ImplicitUsings>
  <Nullable>enable</Nullable>

  <!-- NuGet Package stuff-->
  <Title>Test Library</Title>
  <Authors>Some Author</Authors>
  <Description>Some Description</Description>
  <PackageId>my.website.myId</PackageId>
</PropertyGroup>
```

That is it really. The ItemGroup contains all the magic to make the copy to consumer output happen, AND it even supports transitive dependencies, meanining if project A depends on project B which depends on your package, and project A is the "startup project" then when building project A you will get your file into its output dir, even though there is one "link" in the chain in between.

Now just pack your package using `dotnet pack` in your project folder and you'll find your `.nupkg` in the project `bin/Release/<target framework/` directory :)

If you open the file using 7-zip or similar you'll see that your file resides inside boh `content` and `contentFiles` folders inside the package. 
![image](https://github.com/Matheos96/any-file-in-nuget-package/assets/32064310/1b8da5bb-c369-48f7-9486-08e4028443b4)  
This is exactly what we want as this is from where it will copy the files when the package is consumed, the folders themselves are not copied. In fact, the content folder is actually just there for backwards compitability with older versions of NuGet and you could override the configuration to not include it if you are for example just dealing with .NET (core) projects. You'll also realize that the `contentFiles` directory has subfolders `any/<target framework>/` before your file. This may be a problem if your consuming project is targeting another version of .NET. In this case we need to add the line which overrides "to where" inside the package your file goes. Bare with me. Add the line `<PackagePath>contentFiles\any\any</PackagePath>` to the `<Content ..>` element on the same level as `<Pack>`. This will override the destination of your file **inside** the package and will cause only the _contentFiles_ folder to be created and your file to be placed inside `contentFiles/any/any`. The last _any_ is important as that indicates that the contents inside that folder should be copied to ANY framework target which in this case, is probably a good thing as the file is not framework specific. If you for some reason also want the `content` folder back inside your package, you can add it to the XML tag: `<PackagePath>contentFiles\any\any;content</PackagePath>`.

### The other way, using the example in this repo
If you then either don't have a .csproj at all or your consumer is .NET Framework (which I explained, I personally have not got the above copy thing to work with), please follow these clarification steps for the current example.

Let's again assume your described setup with the file in the project root. You **will** need the `.targets` file available somewhere, if not inside a subfolder in the project then maybe in the project root too? Up to you, I have here assumed you have it in the project root. Assume also you have the `.nuspec` file from this repo in your project root. Now edit the `<files>` element so that it looks like this
```
<files>
      <file src="MyKey.lic" target="content" />
      <file src="My.Package.targets" target="build" /> 
    </files>
```
The trick here is the `src=` path is relative to the nuspec file and the `target` property is the target folder **inside** the nuget package. As you see, here we don't care for any _contentFiles_ folder, we just use _content_. This is because in this case we are kind of making the NuGet package ourselves, and the logic inside the `.targets` file is what is going to cause the copy to happen, and it will take the contents of the embedded `contents` directory and copy it to the consumer's output directory. 
That being said, the `<contentFiles>` tag is still important in the nuspec file. Please update it to this:  
```
<contentFiles>
  <files include="MyKey.lic" buildAction="None" copyToOutput="true" flatten="false" />
</contentFiles>
```
That's it. Don't make any changes to the `.targets` file, the path inside it should be thought of as relative to the `build` folder **inside** the nuget package, not any folder inside your project. So please, don't modify it.

Now just pack your package using either `dotnet pack -p:NuSpecFile=My.Package.nuspec` (leave out the nuspec part if you have it defined in your .csproj like in the example file, or `nuget.exe pack My.Package.nuspec`. You will find your package either in the root of the project dir or in bin/Release/ depending on whether you used `nuget.exe` or `dotnet` :)

Hope this helps, let me know if you have any questions!

**Comment by InteXX** [comment]
What a great answer! I believe your English must be better than mine 😉

Wouldn't you know it—the [solution I arrived at](https://stackoverflow.com/a/78562743), after much spelunking and frustration, exactly mirrors your own advice. I got it from [this answer](https://stackoverflow.com/a/76009014), which includes a link to the source code that processes it all.

I was wondering what that `/any/any` was all about, so I'm glad you clarified that.

I'm not sure why people are claiming the `<PackageCopyToOutput>` element is undocumented—I easily found it [here](https://learn.microsoft.com/en-us/nuget/reference/msbuild-targets). But then again, I knew what I was looking for. That's kind of like cheating—knowing the answers in advance.

Anyway... it turns out the build target may sometimes be necessary after all, under some scenarios (those that don't include the IDE). I learned that last night when I encountered [this blog post](https://blog.tonysneed.com/2021/12/04/copy-nuget-content-files-to-output-directory-on-build/). I find it interesting, to say the least. It's a good trick to have in the toolbox.

**Comment by Matheos96** [comment]
I'm glad you found your answers :) I doubt my English would be better than yours but thank you 😃 

Maybe the docs have been updated to cover `<PackageCopyToOutput>`? I mean, the claims may have been valid when they were made - just a thought.

And yes, the `.targets` is required for the Copy to work as expected. Though, if I remember correctly, the `<PackageCopyToOutput>` + `dotnet pack` "way" automatically creates this file inside the `.nupkg` 😄 

Personally I love it when modern stuff (`.NET` and `dotnet CLI`)just make old, "complicated" stuff like writing `.targets` and `.nuspec` files redundant!

**Comment by InteXX** [comment]
`any/<target framework>/`

I guess I'm still not sure what the first `any` indicates. Are you?

**Comment by InteXX** [comment]
Ah, maybe...

`contentFiles\<language>\<target_framework>`

Ya think?

**Comment by Matheos96** [comment]
Sorry about the late reply!
> Ah, maybe...
> 
> `contentFiles\<language>\<target_framework>`
> 
> Ya think?

Yes, exactly. Language may be `cs` (C#), `fs` (F#), or `vb` (Visual Basic). More often then not I guess this is either `cs`or `any`. Personally never used F# or Visual Basic, though they do belong to the .NET family and apperantly are supported by NuGet too :)

**Comment by InteXX** [comment]
> Language may be cs (C#), fs (F#), or vb (Visual Basic).

Oh. I was thinking 'language' as in `fi-FI` or `en-US`. But I guess not.

**Comment by Matheos96** [comment]
> > Language may be cs (C#), fs (F#), or vb (Visual Basic).
> 
> Oh. I was thinking 'language' as in `fi-FI` or `en-US`. But I guess not.

Ah, no 😄 

Funny you would suggest `fi-FI` as your first example, as I am Finnish 😃  Cheers!

**Comment by InteXX** [comment]
> Funny you would suggest fi-FI as your first example, are you too from Finland?

No, I'm from Alaska...

But it's the only polite thing to do 🙂

**Comment by Matheos96** [comment]
Haha yeh I realised after writing that reponse, hence why the comment above does not match your quote 😋

**Comment by InteXX** [comment]
> the comment above does not match your quote

I know. I couldn't resist.
